// ─── UI Primitives ────────────────────────────────────────────────────────────
export { Button } from './ui/Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './ui/Button'
export { CtaBanner } from './ui/CtaBanner'
export type { CtaBannerProps } from './ui/CtaBanner'
export { Badge } from './ui/Badge'
export type { BadgeProps, BadgeVariant, BadgeSize } from './ui/Badge'
export { Heading } from './ui/Heading'
export type { HeadingProps } from './ui/Heading'

// ─── Cards ────────────────────────────────────────────────────────────────────
export { TestimonialCard } from './cards/TestimonialCard'
export type { TestimonialCardProps } from './cards/TestimonialCard'
export { FaqItem } from './ui/FaqItem'
export type { FaqItemProps } from './ui/FaqItem'
export { HeroOrderCard } from './cards/HeroOrderCard'
export type { HeroOrderCardProps } from './cards/HeroOrderCard'
export { FeatureCard } from './cards/FeatureCard'
export type { FeatureCardProps } from './cards/FeatureCard'
export { StepCard } from './cards/StepCard'
export type { StepCardProps } from './cards/StepCard'
export { ComparisonItem } from './cards/ComparisonItem'
export type { ComparisonItemProps } from './cards/ComparisonItem'
export { ReservationCard } from './cards/ReservationCard'
export type { ReservationCardProps } from './cards/ReservationCard'
export { TeamMemberCard } from './cards/TeamMemberCard'
export type { TeamMemberCardProps } from './cards/TeamMemberCard'
export { ValueCard } from './cards/ValueCard'
export type { ValueCardProps } from './cards/ValueCard'

// ─── Sections ─────────────────────────────────────────────────────────────────
export { TestimonialsSection } from './sections/TestimonialsSection'
export type { TestimonialsSectionProps } from './sections/TestimonialsSection'
export { FaqSection } from './sections/FaqSection'
export type { FaqSectionProps } from './sections/FaqSection'
export type { FaqEntry } from '../utils/data'
export { HeroSection } from './sections/HeroSection'
export type { HeroSectionProps } from './sections/HeroSection'
export { FeaturesSection } from './sections/FeaturesSection'
export type { FeaturesSectionProps } from './sections/FeaturesSection'
export { HowItWorksSection } from './sections/HowItWorksSection'
export type { HowItWorksSectionProps } from './sections/HowItWorksSection'
export { ComparisonSection } from './sections/ComparisonSection'
export type { ComparisonSectionProps } from './sections/ComparisonSection'
export { BuiltForDiscoverySection } from './sections/BuiltForDiscoverySection'
export type { BuiltForDiscoverySectionProps } from './sections/BuiltForDiscoverySection'
export { AboutHeroSection } from './sections/AboutHeroSection'
export type { AboutHeroSectionProps } from './sections/AboutHeroSection'
export { TeamSection } from './sections/TeamSection'
export type { TeamSectionProps } from './sections/TeamSection'
export { ValuesSection } from './sections/ValuesSection'
export type { ValuesSectionProps } from './sections/ValuesSection'

// ─── Layout ───────────────────────────────────────────────────────────────────
export { Header } from './layout/Header'
export { Footer } from './layout/Footer'
export type { FooterProps } from './layout/Footer'
export { RootLayout } from './layout/RootLayout'
export { useFooterCta } from './layout/use-footer-cta'
export type { RootLayoutContext } from './layout/use-footer-cta'
